import React, {Suspense, lazy} from 'react';
import ReactDOM from 'react-dom/client';
import '@fontsource/space-grotesk/400.css';
import '@fontsource/space-grotesk/500.css';
import '@fontsource/space-grotesk/600.css';
import '@fontsource/space-grotesk/700.css';
import '@fontsource/jetbrains-mono/400.css';
import '@fontsource/jetbrains-mono/500.css';
import '@fontsource/geist/400.css';
import '@fontsource/geist/500.css';
import '@fontsource/geist/600.css';
import PublicApp from './PublicApp';
const publicSite = import.meta.env.VITE_PUBLIC_SITE === '1';
const OperatorApp = publicSite ? null : lazy(() => import('./App'));
import './style.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode>{OperatorApp && location.pathname === '/console' ? <Suspense fallback={<div className="console-loading">Opening the operator console…</div>}><OperatorApp/></Suspense> : <PublicApp/>}</React.StrictMode>);
